Release new version with exit code fixes
Ensure the .xsession handles exit codes correctly for
"quit" vs "restart"

diff --git a/release-station-session b/release-station-session
--- a/release-station-session
+++ b/release-station-session
@@ -4,10 +4,8 @@
 
 while true; do
     /usr/lib/pharos-release-station/release-station
-    [ $? -eq 128 ] && continue
-    if [ $? -ne 0 ]; then
-      	zenity --error --text="An error occurred during the previous session. Restarting..."
-    else
-	exit 0
-    fi
+    rv=$?
+    [ $rv -eq 128 ] && continue
+    [ $rv -eq 0 ] && exit 0
+    zenity --error --text="An error occurred during the previous session. Restarting..."
 done	
